export const SHOW_ERROR = 'SHOW_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const VERIFY_AUTHUSER = 'VERIFY_AUTHUSER';
export const VERIFY_AUTHUSER_SUCCESS = 'VERIFY_AUTHUSER_SUCCESS';
export const VERIFY_AUTHUSER_FAIL = 'VERIFY_AUTHUSER_FAIL';
